/**
 * Document Registry
 * 
 * Auto-generated by scripts/register-documents.js
 * Generated on: 2025-10-20T17:48:35.557Z
 * Total documents: 16
 */

export interface HandbookDocument {
  id: string
  name: string
  description?: string
  type: 'pdf' | 'docx' | 'doc' | 'xlsx' | 'other'
  path: string
  size?: string
  lastModified?: string
}

export const documentRegistry: Record<string, HandbookDocument[]> = {
  "/dashboard/handbook/iso-9001/execution-care/methods": [
    {
      "id": "doc-1-2-1-b-beleid-onvrijwillige-zorg-wzd-",
      "name": "2.1.b Beleid onvrijwillige zorg (Wzd)",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/methods/2.1.b Beleid onvrijwillige zorg (Wzd).docx",
      "size": "258.9 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/attitude-leadership": [
    {
      "id": "doc-2-1-4-d-houding-cultuur-en-leiderschap",
      "name": "1.4.d Houding, cultuur en leiderschap",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/attitude-leadership/1.4.d Houding, cultuur en leiderschap.docx",
      "size": "42.8 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-3-governacecode-zorg-2022",
      "name": "Governacecode Zorg 2022",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/preconditions/attitude-leadership/Governacecode Zorg 2022.pdf",
      "size": "4.0 MB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/context-analysis": [
    {
      "id": "doc-4-1-1-d-stakeholdersanalyse-intramuraal",
      "name": "1-1-d-Stakeholdersanalyse-intramuraal",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/context-analysis/1-1-d-Stakeholdersanalyse-intramuraal.docx",
      "size": "190.3 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-5-stakeholdersanalyse-thuiszorg",
      "name": "Stakeholdersanalyse thuiszorg",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/context-analysis/Stakeholdersanalyse thuiszorg.docx",
      "size": "166.6 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/exclusion-criteria": [
    {
      "id": "doc-6-1-6-p-zorgweigering",
      "name": "1.6.p Zorgweigering",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/exclusion-criteria/1.6.p Zorgweigering.docx",
      "size": "46.9 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-7-grenzen-aan-zorg-uitsluitingscriteria",
      "name": "Grenzen aan zorg, uitsluitingscriteria",
      "description": "",
      "type": "doc",
      "path": "/documents/iso-9001/preconditions/exclusion-criteria/Grenzen aan zorg, uitsluitingscriteria.doc",
      "size": "64.0 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/goals": [
    {
      "id": "doc-8-1-3-b-meerjarenbeleidsplan",
      "name": "1.3.b Meerjarenbeleidsplan",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/goals/1.3.b Meerjarenbeleidsplan.docx",
      "size": "53.6 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-9-jaarplan",
      "name": "Jaarplan",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/goals/Jaarplan.docx",
      "size": "55.6 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/laws-regulations": [
    {
      "id": "doc-10-1-7-d-eisen-igj-nieuwe-zorgaanbieders",
      "name": "1.7.d Eisen IGJ nieuwe zorgaanbieders",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/laws-regulations/1.7.d Eisen IGJ nieuwe zorgaanbieders.docx",
      "size": "16.2 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-11-1-7-d-handreiking-verpleegkundig-proces-jan-2020",
      "name": "1.7.d Handreiking verpleegkundig proces jan 2020",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/preconditions/laws-regulations/1.7.d Handreiking verpleegkundig proces jan 2020.pdf",
      "size": "205.3 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-12-1-7-d-inventarisatie-wet-en-regelgeving",
      "name": "1.7.d Inventarisatie wet- en regelgeving",
      "description": "",
      "type": "xlsx",
      "path": "/documents/iso-9001/preconditions/laws-regulations/1.7.d Inventarisatie wet- en regelgeving.xlsx",
      "size": "48.7 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-13-generiek-kompas-samen-werken-aan-kwaliteit-van-bestaan",
      "name": "Generiek Kompas Samen werken aan kwaliteit van bestaan",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/preconditions/laws-regulations/Generiek Kompas Samen werken aan kwaliteit van bestaan.pdf",
      "size": "285.9 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/mission-vision": [
    {
      "id": "doc-14-1-2-d-missie-en-visie",
      "name": "1.2.d Missie, en visie",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/mission-vision/1.2.d Missie, en visie.docx",
      "size": "47.1 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/iso-9001/preconditions/risk-analysis": [
    {
      "id": "doc-15-1-5-d-overzicht-risico-s",
      "name": "1.5.d Overzicht risico-s",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/risk-analysis/1.5.d Overzicht risico-s.docx",
      "size": "46.5 KB",
      "lastModified": "2025-10-20"
    },
    {
      "id": "doc-16-1-5-d-swot-analyse",
      "name": "1.5.d SWOT-analyse",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/preconditions/risk-analysis/1.5.d SWOT-analyse.docx",
      "size": "43.7 KB",
      "lastModified": "2025-10-20"
    }
  ],
  "/dashboard/handbook/hkz-vvt/execution-care/hygiene-infection-prevention": [
    {
      "id": "hkz-vvt-hygiene-1",
      "name": "Hygiëne bij chemotherapie wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/hkz/hkz-vvt/execution-care/hygiene-infection-prevention/Hygiëne bij chemotherapie wijkverpleging en HO .doc",
      "size": "",
      "lastModified": "2025-12-06"
    },
    {
      "id": "hkz-vvt-hygiene-2",
      "name": "Hygiëne en infectiepreventie wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/hkz/hkz-vvt/execution-care/hygiene-infection-prevention/Hygiëne en infectiepreventie wijkverpleging en HO.doc",
      "size": "",
      "lastModified": "2025-12-06"
    },
    {
      "id": "hkz-vvt-hygiene-3",
      "name": "Protocol luchtweginfectie",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/execution-care/hygiene-infection-prevention/Protocol luchtweginfectie.docx",
      "size": "",
      "lastModified": "2025-12-06"
    },
    {
      "id": "hkz-vvt-hygiene-4",
      "name": "Protocol MRSA en BRMO wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/hkz/hkz-vvt/execution-care/hygiene-infection-prevention/Protocol MRSA en BRMO wijkverpleging en HO.doc",
      "size": "",
      "lastModified": "2025-12-06"
    },
    {
      "id": "hkz-vvt-hygiene-5",
      "name": "Protocol norovirus wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/hkz/hkz-vvt/execution-care/hygiene-infection-prevention/Protocol norovirus wijkverpleging en HO.doc",
      "size": "",
      "lastModified": "2025-12-06"
    }
  ],
  "/dashboard/handbook/hkz-vvt/evaluation-end-care/client-satisfaction": [
    {
      "id": "hkz-vvt-client-satisfaction-1",
      "name": "Vragenlijst clienttevredenheid Generiek Kompas 2025",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/evaluations-and-end-of-care/client-satisfaction/Vragenlijst clienttevredenheid Generiek Kompas 2025.docx",
      "size": "",
      "lastModified": "2025-12-07"
    },
    {
      "id": "hkz-vvt-client-satisfaction-2",
      "name": "Handboek Ervaringsmeting Generiek Kompas 2025",
      "description": "",
      "type": "pdf",
      "path": "/documents/hkz/hkz-vvt/evaluations-and-end-of-care/client-satisfaction/Handboek Ervaringsmeting Generiek Kompas 2025.pdf",
      "size": "",
      "lastModified": "2025-12-07"
    }
  ],
  "/dashboard/handbook/hkz-vvt/organization-quality/audit": [
    {
      "id": "hkz-vvt-audit-1",
      "name": "Auditjaarplan",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/organization-quality/audit/Auditjaarplan.docx",
      "size": "",
      "lastModified": "2025-12-07"
    },
    {
      "id": "hkz-vvt-audit-2",
      "name": "Verslagformulier interne auditts",
      "description": "",
      "type": "doc",
      "path": "/documents/hkz/hkz-vvt/organization-quality/audit/Verslagformulier interne auditts.doc",
      "size": "",
      "lastModified": "2025-12-07"
    },
    {
      "id": "hkz-vvt-audit-3",
      "name": "Procedure interne en externe audits",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/organization-quality/audit/Procedure interne en externe audits.docx",
      "size": "",
      "lastModified": "2025-12-07"
    }
  ],
  "/dashboard/handbook/hkz-vvt/organization-quality/participation": [
    {
      "id": "hkz-vvt-participation-1",
      "name": "4.2.d Reglement Raad van Toezicht",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/organization-quality/participation/4.2.d Reglement Raad van Toezicht.docx",
      "size": "",
      "lastModified": "2025-12-07"
    },
    {
      "id": "hkz-vvt-participation-2",
      "name": "4.2.d Informatie over de cliëntenraad",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/organization-quality/participation/4.2.d Informatie over de cliëntenraad.docx",
      "size": "",
      "lastModified": "2025-12-07"
    },
    {
      "id": "hkz-vvt-participation-3",
      "name": "4.2.d Reglement cliëntenraad",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/organization-quality/participation/4.2.d Reglement cliëntenraad.docx",
      "size": "",
      "lastModified": "2025-12-07"
    }
  ],
  "/dashboard/handbook/hkz-vvt/staff/job-descriptions": [
    {
      "id": "hkz-vvt-job-desc-1",
      "name": "2.2.d Functiebeschrijving Helpende Plus",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Functiebeschrijving Helpende Plus.docx",
      "size": "43K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-2",
      "name": "2.2.d Functiebeschrijving Verzorgende IG",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Functiebeschrijving Verzorgende IG.docx",
      "size": "41K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-3",
      "name": "2.2.d Functiebeschrijving Verzorgende",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Functiebeschrijving Verzorgende.docx",
      "size": "40K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-4",
      "name": "2.2.d Huishoudelijk medewerker",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Huishoudelijk medewerker.docx",
      "size": "39K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-5",
      "name": "2.2.d Verpleegkundige niveau 4",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Verpleegkundige niveau 4.docx",
      "size": "42K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-6",
      "name": "2.2.d Wijkverpleegkundige",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d Wijkverpleegkundige.docx",
      "size": "45K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-7",
      "name": "2.2.d. Administratief medewerker",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d. Administratief medewerker.docx",
      "size": "69K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-8",
      "name": "2.2.d. Functiebeschrijving Bestuurder",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d. Functiebeschrijving Bestuurder.docx",
      "size": "72K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-9",
      "name": "2.2.d. Functiebeschrijving Zorgmanager",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d. Functiebeschrijving Zorgmanager.docx",
      "size": "68K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-job-desc-10",
      "name": "2.2.d. HR-functionaris",
      "description": "",
      "type": "docx",
      "path": "/documents/hkz/hkz-vvt/staff/job-descriptions/2.2.d. HR-functionaris.docx",
      "size": "70K",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/hkz-vvt/staff/safe-care-relationship": [
    {
      "id": "hkz-vvt-safe-care-1",
      "name": "Leidraad Veilige zorgrelatie, compact",
      "description": "",
      "type": "pdf",
      "path": "/documents/hkz/hkz-vvt/staff/safe-care-relationship/Leidraad Veilige zorgrelatie, compact.pdf",
      "size": "1.0M",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-safe-care-2",
      "name": "Leidraad Veilige zorgrelatie, op één A4",
      "description": "",
      "type": "pdf",
      "path": "/documents/hkz/hkz-vvt/staff/safe-care-relationship/Leidraad Veilige zorgrelatie, op één A4.pdf",
      "size": "88K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "hkz-vvt-safe-care-3",
      "name": "Leidraad Veilige zorgrelatie, uitgewerkt",
      "description": "",
      "type": "pdf",
      "path": "/documents/hkz/hkz-vvt/staff/safe-care-relationship/Leidraad Veilige zorgrelatie, uitgewerkt.pdf",
      "size": "3.2M",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/iso-9001/execution-care/hygiene-infection-prevention": [
    {
      "id": "iso-9001-hygiene-1",
      "name": "Hygiëne bij chemotherapie wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/iso-9001/execution-care/hygiene-infection-prevention/Hygiëne bij chemotherapie wijkverpleging en HO .doc",
      "size": "67K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-hygiene-2",
      "name": "Hygiëne en infectiepreventie wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/iso-9001/execution-care/hygiene-infection-prevention/Hygiëne en infectiepreventie wijkverpleging en HO.doc",
      "size": "154K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-hygiene-3",
      "name": "Protocol MRSA en BRMO wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/iso-9001/execution-care/hygiene-infection-prevention/Protocol MRSA en BRMO wijkverpleging en HO.doc",
      "size": "100K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-hygiene-4",
      "name": "Protocol luchtweginfectie",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/hygiene-infection-prevention/Protocol luchtweginfectie.docx",
      "size": "43K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-hygiene-5",
      "name": "Protocol norovirus wijkverpleging en HO",
      "description": "",
      "type": "doc",
      "path": "/documents/iso-9001/execution-care/hygiene-infection-prevention/Protocol norovirus wijkverpleging en HO.doc",
      "size": "70K",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/iso-9001/execution-care/job-descriptions": [
    {
      "id": "iso-9001-job-desc-1",
      "name": "2.2.d Functiebeschrijving Helpende Plus",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Functiebeschrijving Helpende Plus.docx",
      "size": "43K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-2",
      "name": "2.2.d Functiebeschrijving Verzorgende IG",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Functiebeschrijving Verzorgende IG.docx",
      "size": "41K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-3",
      "name": "2.2.d Functiebeschrijving Verzorgende",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Functiebeschrijving Verzorgende.docx",
      "size": "40K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-4",
      "name": "2.2.d Huishoudelijk medewerker",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Huishoudelijk medewerker.docx",
      "size": "39K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-5",
      "name": "2.2.d Verpleegkundige niveau 4",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Verpleegkundige niveau 4.docx",
      "size": "42K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-6",
      "name": "2.2.d Wijkverpleegkundige",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d Wijkverpleegkundige.docx",
      "size": "45K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-7",
      "name": "2.2.d. Administratief medewerker",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d. Administratief medewerker.docx",
      "size": "69K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-8",
      "name": "2.2.d. Functiebeschrijving Bestuurder",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d. Functiebeschrijving Bestuurder.docx",
      "size": "72K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-9",
      "name": "2.2.d. Functiebeschrijving Zorgmanager",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d. Functiebeschrijving Zorgmanager.docx",
      "size": "68K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-job-desc-10",
      "name": "2.2.d. HR-functionaris",
      "description": "",
      "type": "docx",
      "path": "/documents/iso-9001/execution-care/job-descriptions/2.2.d. HR-functionaris.docx",
      "size": "70K",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/iso-9001/execution-care/safe-care-relationship": [
    {
      "id": "iso-9001-safe-care-1",
      "name": "Leidraad Veilige zorgrelatie, compact",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/execution-care/safe-care-relationship/Leidraad Veilige zorgrelatie, compact.pdf",
      "size": "1.0M",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-safe-care-2",
      "name": "Leidraad Veilige zorgrelatie, op één A4",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/execution-care/safe-care-relationship/Leidraad Veilige zorgrelatie, op één A4.pdf",
      "size": "88K",
      "lastModified": "2025-12-08"
    },
    {
      "id": "iso-9001-safe-care-3",
      "name": "Leidraad Veilige zorgrelatie, uitgewerkt",
      "description": "",
      "type": "pdf",
      "path": "/documents/iso-9001/execution-care/safe-care-relationship/Leidraad Veilige zorgrelatie, uitgewerkt.pdf",
      "size": "3.2M",
      "lastModified": "2025-12-08"
    }
  ],
  // VCA Documents
  "/dashboard/handbook/vca/risks": [
    {
      "id": "vca-risks-1",
      "name": "Veiligheid boekje Optic Infra 2023",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/Veiligheid_boekje_Optic_Infra_2023.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-risks-2",
      "name": "LMRA jul 23 1.0",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/LMRA_jul_23_1.0.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-risks-3",
      "name": "VGM en LMRA Integraal jul 23",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/VGM_en_LMRA_Integraal_jul_23.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/risks/frm-tra": [
    {
      "id": "vca-frm-tra-1",
      "name": "Taak Risico Analyse aanleg glasvezelkabel grondwerkzaamheden 11 juli 23",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/frm-tra/Taak_Risico_Analyse_aanleg_gla vezelkabel_grondwerkzaamheden_11_juli_23.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/risks/risk-inventory-evaluation": [
    {
      "id": "vca-rie-1",
      "name": "RIE Optic Infra BV",
      "description": "",
      "type": "docx",
      "path": "/vca/risks/risk-inventory-evaluation/RIE_Optic_Infra_BV.docx",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-rie-2",
      "name": "Plan van aanpak RIE Optic Infra",
      "description": "",
      "type": "docx",
      "path": "/vca/risks/risk-inventory-evaluation/Plan_van_aanpak_RIE_Optic_Infra.docx",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-rie-3",
      "name": "Overzicht van de risico's - Optic Infra BV",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/risk-inventory-evaluation/Overzicht_van_de_risicos_Optic_Infra_BV.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-rie-4",
      "name": "Overzicht van maatregelen - Optic Infra BV",
      "description": "",
      "type": "pdf",
      "path": "/vca/risks/risk-inventory-evaluation/Overzicht_van_maatregelen_Optic_Infra_BV.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-rie-5",
      "name": "Actielijst Optic Infra BV",
      "description": "",
      "type": "xlsx",
      "path": "/vca/risks/risk-inventory-evaluation/Actielijst_Optic_Infra_BV.xlsx",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/ohs-awareness": [
    {
      "id": "vca-ohs-awareness-1",
      "name": "Gedrag code",
      "description": "",
      "type": "pdf",
      "path": "/vca/ohs-awareness/Gedrag_code.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/policy/policy-statement": [
    {
      "id": "vca-policy-statement-1",
      "name": "Beleidsverklaring maart 2023",
      "description": "",
      "type": "pdf",
      "path": "/vca/policy/policy-statement/Beleidsverklaring_maart_2023.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/policy/internal-audit-reports": [
    {
      "id": "vca-internal-audit-1",
      "name": "Interne audit Otic Infra 11-07-2023",
      "description": "",
      "type": "pdf",
      "path": "/vca/policy/internal-audit-reports/Interne_audit_Otic_Infra_11-07-2023.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-internal-audit-2",
      "name": "Interne werklocatie audit Optic Infra Korenmolen 80-64",
      "description": "",
      "type": "pdf",
      "path": "/vca/policy/internal-audit-reports/Interne_werklocatie_audit_Optic_Infra_Korenmolen_80-64.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/policy/management-reviews": [
    {
      "id": "vca-management-reviews-1",
      "name": "Directiebeoordeling_jaarplan 2023 VCA2",
      "description": "",
      "type": "pdf",
      "path": "/vca/policy/management-reviews/Directiebeoordeling_jaarplan_2023_VCA2.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/policy/personnel-assessments": [
    {
      "id": "vca-personnel-assessments-1",
      "name": "frm_personeel beoordeling (1)",
      "description": "",
      "type": "doc",
      "path": "/vca/policy/personnel-assessments/frm_personeel_beoordeling_1.doc",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/competence": [
    {
      "id": "vca-competence-1",
      "name": "frm_introductieverklaring_medewerker",
      "description": "",
      "type": "docx",
      "path": "/vca/competence/frm_introductieverklaring_medewerker.docx",
      "size": "",
      "lastModified": "2025-12-08"
    },
    {
      "id": "vca-competence-2",
      "name": "Functietabel",
      "description": "",
      "type": "docx",
      "path": "/vca/competence/Functietabel.docx",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ],
  "/dashboard/handbook/vca/emergency-situations": [
    {
      "id": "vca-emergency-1",
      "name": "KAM-F-007 alarmkaart",
      "description": "",
      "type": "pdf",
      "path": "/vca/emergency-situations/KAM-F-007_alarmkaart.pdf",
      "size": "",
      "lastModified": "2025-12-08"
    }
  ]
};

export function getDocumentsForSection(path: string): HandbookDocument[] {
  // Normalize path - convert new certification paths to old handbook paths for lookup
  let normalizedPath = path;
  
  // If path is in new format (/dashboard/[certification]/...), convert to old format
  const newPathMatch = path.match(/^\/dashboard\/(iso-9001|iso-45001|hkz-kleine-organisaties-2021|hkz-vvt|vca)(?:\/(.*))?$/);
  if (newPathMatch) {
    const [, certification, rest] = newPathMatch;
    normalizedPath = `/dashboard/handbook/${certification}${rest ? `/${rest}` : ''}`;
  }
  
  // Check if normalized path exists in registry
  if (documentRegistry[normalizedPath]) {
    return documentRegistry[normalizedPath];
  }
  
  // Also check original path in case it's already in the old format
  if (documentRegistry[path]) {
    return documentRegistry[path];
  }
  
  // If ISO 45001 path, try to get documents from corresponding ISO 9001 path
  if (normalizedPath.includes('/iso-45001/')) {
    const iso9001Path = normalizedPath.replace('/iso-45001/', '/iso-9001/');
    if (documentRegistry[iso9001Path]) {
      // Return the same documents but update paths for ISO 45001
      return documentRegistry[iso9001Path].map(doc => ({
        ...doc,
        id: doc.id.replace('iso-9001', 'iso-45001'),
        path: doc.path.replace('/iso-9001/', '/iso-45001/')
      }));
    }
  }
  
  // If ISO 9001 path, try to get documents from corresponding ISO 45001 path
  if (normalizedPath.includes('/iso-9001/')) {
    const iso45001Path = normalizedPath.replace('/iso-9001/', '/iso-45001/');
    if (documentRegistry[iso45001Path]) {
      return documentRegistry[iso45001Path];
    }
  }
  
  // If HKZ Kleine organisaties 2021 path, try to get documents from corresponding ISO 9001 path
  if (normalizedPath.includes('/hkz-kleine-organisaties-2021/')) {
    // Check if exact path exists in registry first
    if (documentRegistry[normalizedPath]) {
      return documentRegistry[normalizedPath];
    }
    
    // Try to get documents from corresponding ISO 9001 path (same structure)
    const iso9001Path = normalizedPath.replace('/hkz-kleine-organisaties-2021/', '/iso-9001/');
    if (documentRegistry[iso9001Path]) {
      // Return the same documents but update IDs for HKZ (keep ISO9001 paths since files exist there)
      return documentRegistry[iso9001Path].map(doc => ({
        ...doc,
        id: doc.id.replace(/iso-9001/g, 'hkz-kleine-organisaties-2021').replace(/iso_9001/g, 'hkz_kleine_organisaties_2021')
      }));
    }
    
    // Try to find documents in the registry with matching path patterns
    const hkzPath = normalizedPath.replace('/dashboard/handbook/', '');
    const matchingPaths = Object.keys(documentRegistry).filter(regPath => 
      regPath.includes(hkzPath) || hkzPath.includes(regPath.replace('/dashboard/handbook/', ''))
    );
    
    if (matchingPaths.length > 0) {
      return matchingPaths.flatMap(p => documentRegistry[p]);
    }
    
    // Return empty array - documents will be added when they're downloaded
    return [];
  }
  
  // If HKZ VVT path, try to get documents from hkz folder structure
  if (normalizedPath.includes('/hkz-vvt/')) {
    // Check if exact path exists in registry first
    if (documentRegistry[normalizedPath]) {
      return documentRegistry[normalizedPath];
    }
    
    // Try to find documents in the registry with matching path patterns
    const hkzPath = normalizedPath.replace('/dashboard/handbook/', '');
    const matchingPaths = Object.keys(documentRegistry).filter(regPath => 
      regPath.includes(hkzPath) || hkzPath.includes(regPath.replace('/dashboard/handbook/', ''))
    );
    
    if (matchingPaths.length > 0) {
      return matchingPaths.flatMap(p => documentRegistry[p]);
    }
    
    // Return empty array - documents will be added when they're downloaded
    return [];
  }
  
  // If VCA path, try to get documents from vca folder structure
  if (normalizedPath.includes('/vca/')) {
    // Check if exact path exists in registry first
    if (documentRegistry[normalizedPath]) {
      return documentRegistry[normalizedPath];
    }
    
    // Try to find documents in the registry with matching path patterns
    const vcaPath = normalizedPath.replace('/dashboard/handbook/', '');
    const matchingPaths = Object.keys(documentRegistry).filter(regPath => 
      regPath.includes(vcaPath) || vcaPath.includes(regPath.replace('/dashboard/handbook/', ''))
    );
    
    if (matchingPaths.length > 0) {
      return matchingPaths.flatMap(p => documentRegistry[p]);
    }
    
    // Return empty array - documents will be added when they're downloaded
    return [];
  }
  
  return [];
}

export function getAllDocuments(): HandbookDocument[] {
  return Object.values(documentRegistry).flat()
}

export function searchDocuments(query: string): HandbookDocument[] {
  const lowerQuery = query.toLowerCase()
  return getAllDocuments().filter(doc => 
    doc.name.toLowerCase().includes(lowerQuery) ||
    doc.description?.toLowerCase().includes(lowerQuery)
  )
}
